services:
  auth:
    target: "http://localhost:9001/auth/"
    routes:
      "/api/v1/sign-up/user": []
      "/api/v1/validate-email/user": []
      "/api/v1/sign-in/user": []
      "/api/v1/sign-up/sysadmin": []

  tenant-management:
    target: "http://localhost:9002/tnt"
    routes:
      "/api/v1/heartbeat": ["sys_admin"]
      "/api/v1/tenants": ["sys_admin"]
      "/api/v1/tenants/{id}/deactivate": ["sys_admin","admin"]
      "/api/v1/tenants/{id}": ["sys_admin","user","admin"]

  geo-track:
    target: "http://localhost:9003"
    routes:
      "/loc/api/v1/submit": ["user","admin","sys_admin"]
      "/loc/api/v1/heartbeat": ["user","admin","sys_admin"]
